### ISSUE TITLE
MSVC 2013 compile error

### ISSUE THREAD

**Issue by inspirit** [ALSchwalm/lfpAlloc#1]
Hi
I was trying to compile the project with MSVC 2013 and it was failing because of this line:
https://github.com/ALSchwalm/lfpAlloc/blob/master/lfpAlloc/ChunkList.hpp#L16
It says that array cant be zero sized. seems like it somehow tried to compile
Cell<0x0> structure...

**Comment by ALSchwalm** [comment]
I don't have a MSVC installation on hand to test, but I believe lfpAlloc will probably fail to compile due to current limitations of that compiler. Could you post a more complete error message?

**Comment by inspirit** [comment]
i modified a struct by adding static assert:

```
template<size_t Size>
struct Cell {
    static_assert(Size > 0, "Cell Size should be greater than zero.");
    uint8_t val[Size];
    Cell* next = this+1;
};
```

MSVC error:
error C2338: Cell Size should be greater than zero

and afterwards:

```
ChunkList.hpp(16): error C2229: struct 'lfpAlloc::Cell<0x00>' has an illegal zero-sized array
```

I just tried to initialize allocator:

```
lfpAlloc::Allocator<uint8_t,16> _task_allocator;
```

changing pools number doesn't help.

on Mac and Linux everything is fine though...

**Comment by ALSchwalm** [comment]
This should be resolve  by 8e7e154c, can you test it?

**Comment by inspirit** [comment]
now it seems to be not able to find Cell fields:
```
Error	241	error C2039: 'next' : is not a member of lfpAlloc::Cell<0x00>'	 Pool.hpp	31
Error	241	error C2039: 'val' : is not a member of lfpAlloc::Cell<0x00>'	 Pool.hpp	33
```

**Comment by inspirit** [comment]
sorry new error message was my fault!
it compiles now. i will need to run some tests to see if everything is fine though but at first glance it looks good!

thanx

**Comment by inspirit** [comment]
seems to be fine now. i wonder why it silently compiled with clang and gcc while MSVC was able to spot that...
